### PR TITLE
fix docker cuda is not available

### PR DESCRIPTION
**Pull request by min-star**

### CODE REVIEW

**Comment by henryruhs** [comment]
Does not work:

```
#0 1.825 Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
#0 1.833 Errors were encountered while processing:
#0 1.833  python3.10-minimal
#0 1.833  python3.10
#0 1.837 E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Also you should not disable `RUN pip uninstall onnxruntime -y`

**Comment by min-star** [comment]
yes,i pip uninstall onnxruntime in the container,because it is uninstalled failed when build the image

**Comment by henryruhs** [comment]
there was just an `-y` needed. anyway... the problem is still that we cannot install python.

**Comment by min-star** [comment]
it's strange,it's ok with me

**Comment by henryruhs** [comment]
destroy the image and rebuild from scratch

**Comment by min-star** [comment]
actually  i try it twice,^_^

**Pull request closed without merging**
